### ISSUE TITLE
Update tooltip % logic on sentencing sankey

### ISSUE THREAD

**Issue by jjdressel11** [Recidiviz/public-dashboard#137]
It is possible for individuals to be serving both incarceration and probation sentences simultaneously. This means that the sum of the "Probation" and "Incarceration" categories is higher than the total number of people currently under DOCR control.

The percentage calculations in the sankey diagram tooltips are using the probation + incarceration sum as the denominator. These two %s should sum to 100%:

![image](https://user-images.githubusercontent.com/9345233/89355406-2abe0980-d670-11ea-86c7-28f0fbee1945.png)

Simple approach: Remove the %s from the tooltips and only show raw counts.

Complete approach: Have the % calculation use the denominator value of the total number of unique people that fall into the category in the diagram (this is provided in the `total_population_count` field in the data).

**Comment by hobuobi** [comment]
Let's create a third category that are serving both probation and incarceration sentences.

**Comment by jjdressel11** [comment]
Required copy updates spelled out [here](https://docs.google.com/document/d/16Cr_mSpjyvOp4bw8GI-s5Z80vuFqmQAdfTRQL1VNIgs/edit?usp=sharing).
