### ISSUE TITLE
Accessibility Update (fonts, colors)

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#143]
Update the styling of the site to be in line with the font size and color scheme defined [in Figma.](https://www.figma.com/file/oBpZbRPT44MDwXaXgHz7M6/ND%2C-Public-Dashboard-(Desktop)?node-id=1341%3A731)

Includes font size changes and updating the color schemes for some visualizations to be discernable on sight (more colors/contrast).

**Comment by macfarlandian** [comment]
#138 was part of this but the updated dataviz colors are TK
