### ISSUE TITLE
Update the "Methodology" content on the homepage to provide additional context (or remove).

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#145]
When you click on the "Methodology" button on the homepage, we just give some very general methodology notes that apply to all of the pages/visualizations, but provide no useful context on what someone should normally expect when they see this button. 

We should update this copy to better orient users and help them understand what will _normally_ show up when you click this component. 

<img width="500" alt="Screen Shot 2020-08-05 at 9 22 10 AM" src="https://user-images.githubusercontent.com/7134733/89438021-25f36700-d6fd-11ea-8ca8-fda39e720044.png">

Alternatively, we could remove the Methodology button entirely from the homepage.

**Comment by macfarlandian** [comment]
this issue has been superseded by v2
