### ISSUE TITLE
Change the color of the dropdown component when a non-default option is selected. 

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#146]
Currently, when a user selects an slicing option from the dropdown, the change is reflected in the visualization but not thoroughly reflected in the UI.

Changing the background color of the component when it is "active" (that is, a non-default option is selected) could help users understand and remember that they have turned on a slicing/filtering option. This is common practice in other UI and visualization applications. 

For example, see the styling of the dropdown component on the Racial Disparities page: 
<img width="929" alt="Screen Shot 2020-08-05 at 9 26 47 AM" src="https://user-images.githubusercontent.com/7134733/89438541-cb0e3f80-d6fd-11ea-8a3f-5a1b64a9eef3.png">

Already included in the design spec (Label: [ACTIVE]). See [here.](https://www.figma.com/file/oBpZbRPT44MDwXaXgHz7M6/ND%2C-Public-Dashboard-(Desktop)?node-id=1341%3A731)

**Comment by macfarlandian** [comment]
this is fixed in #138
