### ISSUE TITLE
Mobile infobox carries over the previously selected demographic label 

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#171]
When investigating different bars on the vertical bar charts, it seems that the demographic label (e.g. "Native American") **from the previous selection ** is used instead of the one you're actually selecting. Doesn't seem to be an issue for other chart types, but will investigate more deeply. 

See below GIF. 

<img src="https://user-images.githubusercontent.com/7134733/89923093-e3c29d80-dbb4-11ea-840b-c2ea4ac20b74.gif" width="300"/>

**Comment by macfarlandian** [comment]
this has been superseded by v2
