### ISSUE TITLE
Population Over Time visualization

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#176]
During the original timeline, we deprioritized making data visualizations for almost all historical / trend data due to various complexities. However, showing **aggregate populations over time** can be a very powerful visualization if done properly given that it is: 
- Directly related to understanding progress towards decarceration goals. 
- Particularly interesting during COVID-19 times. 
We should investigate how we can make this happen, both regarding calculations and potential designs.

**Comment by macfarlandian** [comment]
@hobuobi for the U,I I still need final copy for the section heading and description on the Prison, Parole, and Probation pages
