### ISSUE TITLE
Wrong location for Grand Forks PNP office on Parole page

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#210]
**Describe the bug**
Grand Forks PNP office should be in a different location that what is currently on the Parole map. 

**Expected behavior**
![image.png](https://images.zenhubusercontent.com/5efa0f1acabfc83e776b1102/b0630fb9-a72a-408c-9c8c-b48fc4ec0f21)
_Should be in approximately the location of the X._

Actual address is 311 S. 4th St. Grand Forks, ND 58201. Lat/Long: (47.922020, -97.026180).

**Comment by macfarlandian** [comment]
@hobuobi is this also wrong for the ND private dashboard? Pretty sure this location data came from the same source as that

**Comment by macfarlandian** [comment]
this was a data file issue; no code change required to fix.
