### ISSUE TITLE
Recidivism rate over time chart

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#232]
This should be one or more bar charts on the ND Sentencing page (similar to the length-of-stay visualization on the Prison page) that depicts the recidivism rates for a single follow-up period over time. 

It is a more focused view of the same data used for #216 so it should use the same metric file from the API.

Refer to the mocks for more detailed requirements.

**Comment by macfarlandian** [comment]
@hobuobi I have a few questions about the scope of this feature ...

1. I am not totally clear on whether we want to just present the three-year followup rate in this section, or if there will be a choice between several followup periods. (The mocks seem to be depicting kind of a mix of both.) If there are to be multiple followup periods, which ones should they be? 
1. Related to that, the introductory copy in the mocks seems to assume that the text will change dynamically based on which followup period is selected. That is not currently supported on the detail pages and has not been a requirement for any of the other sections. Do we really want to bring that in scope here, or can we just come up with a static title and description that will suffice?
1. Lastly, the copy is not final in any case, it has some placeholders and odd phrasing that need to be resolved as part of this ticket (exactly how depends on the answers to the previous questions). This is not technically a question, just something I am bringing to your attention

**Comment by hobuobi** [comment]
1. Multiple follow-up periods! 1,3, and 5 would be ideal. 
2. Yeah let's nix the dynamic text thing! The title of that section should now read "How has the recidivism rate changed over time?"
3. Very true. Let's create another ticket for it and I'll make sure I tackle that either tomorrow or early in next week's sprint.
