### ISSUE TITLE
Expand race/ethnicity categories beyond ND

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#314]
In the initial version of Spotlight we tailored the race & ethnicity categories to the particular demographic makeup of North Dakota (namely, we decided to group "ASIAN" and "NATIVE_HAWAIIAN_PACIFIC_ISLANDER" with "OTHER" due to the low numbers, and we noted this in our methodology text. 

This solution is obviously not going to work for every state. To facilitate the onboarding of new states, we need to decide: 

- do we abandon this customization and use the standard categories for all states? 
- or do we allow state-by-state customization and come up with a way to do it programmatically? 

Implementation plan TBD based on the outcome of that decision.

**Comment by macfarlandian** [comment]
@hobuobi is it safe to say, at this point, that the ability to customize the demographics per state is a must-have? Or is the idea of applying the full set of categories to every state still on the table? That is the crux of the implementation question that has to be answered before we can proceed with this

**Comment by macfarlandian** [comment]
I am like 95% sure it's a must-have FWIW @hobuobi  but just want to make sure before I put the work in

**Comment by hobuobi** [comment]
Reasoning out loud: 
- I'm 100% sure it's a must-have in the long run -- it's the communities affected by the criminal justice system (or just the populations that are well-represented in the state in general) are likely different from state to state. 
- I'm conflicted as to whether we need it *right now*given that PA's numbers for Asian, Native American, *and* NH/PI individuals are similar to North Dakota's (that is, the "Other" category* is larger than the Asian population). Thinking aloud through the options: 
    - We could do it now to _include_ all the populations, despite the fact that some of the populations are tiny. Doing so is maybe a good practice for the sake of inclusion, but they'll also barely be visible or interactive on some visualizations since they're so small (not applicable for all of the visualizations though, so probably a moot point). 
    - We could do it now to actually _exclude_ all of the aforementioned race categories that are less than "Other," and put them in the "Other" category (and note this in the methodology, as we do for ND). Those categories should probably be available in the actual data download so we're not omitting anything. 
    - We could **not** do any of this right now, since again, all the populations we're talking about are super small anyway, and the current solution will still work for showing the most dominant populations in PA (primarily just White and Black populations). 

Ultimately, I think I'm leaning towards building it now since we have the time to, but given all this, curious for your thoughts. 

* Side note: we might want to find a different term instead of "other," since that can be a bit loaded/problematic. Not urgent though, just curious if there are alternative best practices.

**Comment by macfarlandian** [comment]
Something I have realized more recently is that I'm not actually sure that all of the categories we have are even guaranteed to be used by every state, e.g. the NHPI group seems to be missing from the PA data entirely. I don't know if that's due to internal or external methodology (@ChineduOzodi has been looking into it but maybe @jjdressel11 already knows the answer?). If anything that strengthens the case for doing it now.

That said, I am generally of the opinion that we should move away from collapsing any of these categories together unless it's absolutely necessary (as in, the state collapses them in the raw data they provide us so we have to match that methodology). The small group data can be a little noisy but it's not like we are doing statistics on top of them or anything like that, just reporting the numbers is not really misleading or inaccurate.

**Comment by macfarlandian** [comment]
@hobuobi I was looking this over and realized there was another point I wanted to clarify. Currently all of the collapsing is done in the calculation pipeline — meaning that what's in the download and what's visible in the charts are exactly the same. We have avoided doing any aggregation on the fly as you describe in option 2 above. It's not to say we couldn't come up with a solution that satisfies that, but it would be a pretty significant increase in scope and complexity. 

That is, in ND currently the categories are collapsed in the download as well as the UI, and simply expanding the existing functionality to other states means the same would be true for all of them too.

**Comment by macfarlandian** [comment]
Given that I would suggest that maybe we explicitly collapse `NATIVE_HAWAIIAN_PACIFIC_ISLANDER` into `OTHER` for Pennsylvania; that way we don't have a completely empty category and we also don't exclude any individuals in that category if they appear in future data
