### ISSUE TITLE
Remove roles assigned to firebase-adminsdk-qxmen service account

### ISSUE THREAD

**Issue by jessex** [Recidiviz/public-dashboard#352]
**What needs to be done? Why does it need to be done?**
This service account appears to have been with our Public Dashboard Staging GCP project since the inception of the project, but GCP's Security Command Center (SCC) has an active `ADMIN_SERVICE_ACCOUNT` finding which is unhappy about the admin permissions granted to that service account. GCP's built-in IAM recommendations tool is reporting that the service account has used neither of the roles that are currently granted to it and should be removed.

This ticket is to track removing both of the roles currently assigned to the service account:
- Firebase Admin SDK Administrator Service Agent
- Service Account Token Creator

**Additional context**
Screenshot of finding:
<img width="1201" alt="Screen Shot 2021-03-08 at 15 33 42" src="https://user-images.githubusercontent.com/431895/110390768-b55e5100-8023-11eb-98d3-ef1d9b592e9d.png">

Screenshot of all permissions being recommended for deletion:
<img width="1602" alt="Screen Shot 2021-03-08 at 15 27 36" src="https://user-images.githubusercontent.com/431895/110390206-dbcfbc80-8022-11eb-9cab-f7de2eba1f21.png">

**Comment by macfarlandian** [comment]
@jessex this sounds good to me! we are not using this service account for anything.

**Comment by jessex** [comment]
Thanks, @macfarlandian! I just applied the IAM recommendations which removed both roles. Because there are no longer any roles granted to the account, it no longer appears on the IAM Permissions page. 

Re-open this if you notice any unexpected behavior in staging. Thanks!
