### ISSUE TITLE
Resolve security alert for react-dev-utils

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#359]
**What needs to be done? Why does it need to be done?**
Based on my investigation of [this alert](https://github.com/Recidiviz/public-dashboard/security/dependabot/yarn.lock/react-dev-utils/open), it should simply be dismissed. It is a transitive dependency of Create React App but users of that package are unaffected; we do not use the offending function in our code directly.

**Additional context**
The alternative would be a major version upgrade to `react-scripts`, which would introduce a number of breaking changes to developer tooling with no practical benefit with regard to this issue.

**Comment by macfarlandian** [comment]
alert dismissed

**Comment by jessex** [comment]
Thanks, @macfarlandian! This seems reasonable to me.
