### ISSUE TITLE
v2.x polish

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#373]
**What needs to be done? Why does it need to be done?**
Minor improvements identified during v2.0 QA but deemed not to be launch blocking, in rough order of priority:

- [x] ~scroll position is not consistent when the page first loads; user does not stay at the section indicated by the url (this may be a larger issue, in which case break out to its own ticket) (HO: Would move out of launch prio list for now -- possible patch could be to~ disabled for v2.0. this is more work than mere polish, see #395 
- [x] [iOS] navigation menu doesn't scroll on mobile when it doesn't fit
- [x] [iOS] broken sankey highlight states (edges turn black instead of gradient after clearing highlight state) 
![IMG_2378](https://user-images.githubusercontent.com/5385319/112523041-8e11be80-8d5b-11eb-8526-4d30f8266a89.png)
- [x] [iOS] recidivism bar labels get cramped on small screens (not overlapping on iPhone 7 but just barely) 
![IMG_2379](https://user-images.githubusercontent.com/5385319/112523046-8eaa5500-8d5b-11eb-9720-5aed549be18a.png)
- [x] [iOS] stacked dropdowns on racial disparities don't line up 
![IMG_2380](https://user-images.githubusercontent.com/5385319/112523044-8eaa5500-8d5b-11eb-90e3-c201f4a1a0f0.png)
- [x] ~[iOS] have to double tap the recidivism multiple selection menu sometimes to select a year? (not totally broken but a little confusing and inconsistent) (HO: would move this up, but not above the launch prio line)~ big enough to warrant its own ticket, see #400 
- [x] [IE 11] footer contents aligned to top instead of bottom
- [x] [IE 11] inconsistent arrow placement on dropdown buttons (sometimes fine, sometimes not aligned ... seems to happen in VirtualBox but not on Browserstack which is a little suspect) 
![Screen Shot 2021-03-25 at 11 21 17 AM](https://user-images.githubusercontent.com/5385319/112523733-4f303880-8d5c-11eb-864f-114b46b559ea.png) ![Screen Shot 2021-03-25 at 11 21 21 AM](https://user-images.githubusercontent.com/5385319/112523745-50f9fc00-8d5c-11eb-9e02-360c023102ab.png)
- [x] remove "scroll >>" indicators from narrative introductions

**Additional context**
Add any other context about the task here.

**Comment by agr0n** [comment]
Should we add "Remove 'Scroll' thingy" here?
