### ISSUE TITLE
Multistate exploration

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/public-dashboard#377]
**What needs to be done? Why does it need to be done?**
There are some structural prerequisites to getting PA onto Spotlight that need to be explored to come up with a solution: 
- the site needs to redirect you to the right state based on the URL domain
    - ideally we can replicate this with multiple staging domains to avoid a "testing in prod" situation
    - the centralized "multi-state" Spotlight experience is likely not in scope for the PA launch, so Spotlight will still only live under .gov subdomains for now
    - currently there is a centralized staging site - what to do with that? 
- once redirected to the right tenant, you should also be restricted to that tenant - meaning any navigational elements that would point you to another tenant's page should be disabled (not that there currently are any), and any direct visits to urls outside the current tenant should be intercepted and redirected to an appropriate page
    - should the API also be restricted somehow to only serve tenant data to an appropriate referrer? 

**Additional context**
n/a

**Comment by macfarlandian** [comment]
see this [design document](https://paper.dropbox.com/doc/Spotlight-Coast-to-Coast--BIBOxtr0o6ZBfIetVfhdlWPdAQ-UqU4dVp6SsXYumTC0I8kt) for the fruits of said exploration

**Comment by jessex** [comment]
Design doc looks great to me, @macfarlandian! I only left a few remarks but I think the approach is sound. :+1:
