### ISSUE TITLE
Configure tenant-specific staging subdomains

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#390]
**What needs to be done? Why does it need to be done?**
Update DNS records and Firebase configuration as needed to implement and verify domain matching in staging. 

**Additional context**
[Design doc](https://paper.dropbox.com/doc/Spotlight-Coast-to-Coast--BIuU23kLFmFGg_d4zCIzy1IOAQ-UqU4dVp6SsXYumTC0I8kt)

**Comment by jessex** [comment]
Created the required DNS records and shared proof with @macfarlandian offline.

**Comment by macfarlandian** [comment]
DNS has propagated and I have updated the Firebase and Auth0 configurations; the new subdomains (us-nd.spotlight-staging.recidiviz.org, us-pa.spotlight-staging.recidiviz.org) are now serving up the staging environment.
