### ISSUE TITLE
Populate the list of expected localities for PA

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#404]
**What needs to be done? Why does it need to be done?**
The list of expected prison facilities and parole offices, along with their properly formatted display names, needs to be derived from the calc process and/or other data sources and added to the PA content object.

**Additional context**
the data seems to enumerate out-of-state localities in a way that the ND exports did not (they were all grouped as "other" when they appeared, e.g. in Probation data). That may need to be addressed in the calc pipeline

**Comment by hobuobi** [comment]
Our approach for this should be to only highlight the **primary facilties/institutions** at PADOC, which should be regularly reflected in their monthly reports. I've marked the relevant facilities in the PA Spotlight Scope Tracker as a filter view on the Facilties sheet: https://docs.google.com/spreadsheets/d/1dF4gthRy-UkXWKgb2D_TqweJhRmlStXxqYWhUeJ93SI/edit#gid=1542429793&fvid=50969230

There is a separate question as to whether or not we should mention anything about Parole Violator Centers, but this should be considered lower priority for launch.

**Comment by macfarlandian** [comment]
@hobuobi does this mean that any facilities not on this list should be excluded from the calculations? Or do we want to group them together as "other" or something

**Comment by hobuobi** [comment]
I think grouping everything else as Other is probably good -- good call!

**Comment by macfarlandian** [comment]
@colincadams sounds like we need a companion task for the backend to complete this?
