### ISSUE TITLE
Finalize PA copy

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#405]
**What needs to be done? Why does it need to be done?**
Includes an introductory blurb for the homepage plus any edits that may be requested internally or externally.

**Additional context**
n/a

**Comment by hobuobi** [comment]
Drafting final copy [here](https://docs.google.com/document/d/1oVd3S-L5RM-ho_TA0TJ3VCpwEsXtMXdepxdW9PtD30Y/edit)! Summarizing the biggest changes: 
- Added copy for the landing page (largely taken from the PADOC mission statement). 
- Need to investigate the prominence of new admissions -- the current copy presumes that new admissions are a smaller proportion of total admissions. 
- Might want to add some context on why the prison population has grown and shrunk (mandatory minimums, covid, etc)
