### ISSUE TITLE
additional analytics instrumentation

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#410]

**Comment by colincadams** [comment]
pending doc from humphrey

**Comment by hobuobi** [comment]
aforementioned doc! https://docs.google.com/document/d/1xyKmDP6QWxqk_z288rrANtuTz4AS0HL-m68L54Z914Q/edit#

very much a stub, feel free to edit / add other ideas. Also copying the things I wrote in that doc down below for convenience: 

- [P0] Which narratives get the most attention/views? 
- [P0] How far do people make it through a given narrative before leaving? 
- [P1] How long do people engage with the different narratives? 
- [P0] How do people navigate away from the homepage (via the Data Narratives dropdown? Via the big links at the bottom?) 
- [P1] Are people interacting with the wayfinder? In what way (arrows or hovering over the section segments)?

**Comment by macfarlandian** [comment]
This looks great to me so far. In terms of implementation, we basically already have the first P0 based on pageviews, and the remainder are attainable just by tracking clicks on the various navigation elements and tracking when the page sections come into view. That will give us better data for time on page as well as making the other questions answerable.
