### ISSUE TITLE
solution for PA PVCs

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#411]

**Comment by hobuobi** [comment]
Current understanding is as follows: 
- Parole Violator Centers (along with State Drug Treatment Program centers) are a **subset** of Community Correction Centers, which show up as facilities in our data. 
- Community Corrections Centers will often hold a mix of PVC, SDPT, and regular supervision folks. We don't know the PVC or SDPT status of specific individuals (@colincadams to confirm?).
- We can get a vague understanding of which CCCs contain SDPT or PVC folks via the [Community Corrections Report](https://drive.google.com/file/d/1n2bYDcu1n67GQqC4B75tZdHHuD6ZmdQr/view?usp=sharing). 

It would probably still be valuable to talk about these different programs and alternatives that the state runs, but difficult to show anything on a real-time basis until we are regularly ingesting some information on them. 

**Proposed alternative would be to have a text-only section in the Parole narrative that describes the programs, plus any information we might have on their effectiveness.** This would probably be a P1 for launch. If that sounds good to folks, I can follow-up with proposed copy and maybe run it by Bret/other PADOC leadership.

**Comment by colincadams** [comment]
@hobuobi do we still want a text only section? or is this just captured by the facility category change, and will be captured by adding copy to that section?

**Comment by colincadams** [comment]
Decision: Duplicate first section for CCC, exclude CCC from historical and admissions.

Need to clarify with Bret on who is included in the recidivism metric.

**Comment by macfarlandian** [comment]
@hobuobi are we doing a breakdown by facility for the CCCs? or just the total population? (I don't think we have completely mapped all of the facility IDs in the data to their proper names, so we'll need to finish tracking those down or otherwise handle them if so)

**Comment by hobuobi** [comment]
Just the total population should be fine for now! 
If time: technically there is a mapping from facility to 3# code in [this report](https://drive.google.com/file/d/1314EgBHlUcK-_zA2ScRnpZxYaZ3I7rn-/view?usp=sharing), but I haven't had the time to see if its fully comprehensive of the CCC facilities we have on hand. Might be worth a quick check against the numbered facilities [here](https://docs.google.com/spreadsheets/d/1dF4gthRy-UkXWKgb2D_TqweJhRmlStXxqYWhUeJ93SI/edit#gid=1542429793)?

**Comment by macfarlandian** [comment]
@hobuobi this looks good compared to the spreadsheet but I'll check it again against the live data once the new view is broken out
