### ISSUE TITLE
[Spotlight] Add 'dashboard.cor.pa.gov' as a domain name to firebase

### ISSUE THREAD

**Issue by colincadams** [Recidiviz/public-dashboard#428]
**What needs to be done? Why does it need to be done?**
Configure the new domain as a Firebase Custom Domain, then provide the required DNS settings to PA staff so they can configure on their end.

**Additional context**
Nothing will be displayed on the site until we activate PA in production with a feature flag, so configuring this before the desired launch date should not leak anything.

**Comment by macfarlandian** [comment]
Configuration for this is complete in both Firebase and the PA DNS provider and we've been able to verify it against the live site. Just waiting a few more hours for the DNS to fully propagate and for Firebase to provision the SSL certificate. Will update and close when that happens.

**Comment by macfarlandian** [comment]
all done and working!
