### ISSUE TITLE
High-level security vulnerability: set-value

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/public-dashboard#481]
**What needs to be done? Why does it need to be done?**
A high-level security vulnerability has been detected by Dependabot in this project.

Per our SLA, high-level security vulnerabilities need to be addressed within 30 days. The deadline for resolution is October 17, 2021.

**Additional context**
https://github.com/Recidiviz/public-dashboard/security/dependabot/spotlight-api/yarn.lock/set-value/open

**Comment by phenggeler** [comment]
Hi @macfarlandian, just a friendly ping about this vulnerability and its Oct 17th deadline for resolution. Is it possible to get this one pulled into the next sprint?

Thanks!

**Comment by macfarlandian** [comment]
yeah sorry i've had a bunch of these pile up, was planning to get to them all by next week!

**Comment by phenggeler** [comment]
Awesome, thanks @macfarlandian!
