### ISSUE TITLE
Use design system Tooltip component in charts

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#512]
**What needs to be done? Why does it need to be done?**
The design system now includes a `Tooltip` component that can be used to wrap tooltip content in the charts defined here. It should be substituted for any custom styles used. The chart-specific Tooltip component in this application has additional functionality for formatting contents and that should remain in place.

**Additional context**
Requires an update to v2.7.0 or higher; this is not expected to introduce any breaking changes to existing design system usage.

**Comment by terryttsai** [comment]
Closing issue, see https://github.com/Recidiviz/public-dashboard/pull/533#discussion_r848932852
