### ISSUE TITLE
Implement state-specific staging access

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#540]
In the process of preparing a Spotlight dashboard for launch, we want to be able to share a **fully-functional but private** version of the dashboard with contacts in the associated agency. However, the current staging site gives the logged-in user access to the staging site for all states that have been activated. This has the (likely) chance of exposing data to state actors that do not have permission to view other states’ data. 

As such, we need to be able to create staging accounts that have restricted access (e.g., only have access to the state where they work). Proposed directions (paraphrased from @macfarlandian ’s words): 
- Tag people with their state code and then send that metadata to the backend in the auth token
- Impose restrictions on the frontend (we already have this feature tied to the domain name, and it could be extended to check the auth metadata).

**Comment by lilidworkin** [comment]
Thoughts/pointers for @terryttsai :
* The staging site is https://spotlight-staging.recidiviz.org. You can see how (after you signup) that page links out to all states, which is what we need to fix
* [Firebase hosting ](https://console.firebase.google.com/project/spotlight-staging-f0154/overview)for Spotlight staging app (If you're not able to see this, then file an access change ticket with Peter!)
* Some information about Auth0 and Spotlight [here](https://github.com/Recidiviz/public-dashboard/tree/88f87c413ece3fa81f384d10dd56f094bfb6bcc1/spotlight-client#environment-variables), and also more in-depth [here](https://github.com/Recidiviz/public-dashboard/tree/88f87c413ece3fa81f384d10dd56f094bfb6bcc1/spotlight-client/auth0)

**Comment by terryttsai** [comment]
So I implemented the front-end behavior in this PR: https://github.com/Recidiviz/public-dashboard/pull/544. Check out the loom. The user is automatically redirected to the state their Auth0 account is assigned to, and they're not allowed to visit any other states if they try to access other states' URLs.

A few questions:

1. If a user does not have a state_code set, currently they will see the old behavior, which is they will land on a page listing all available states, and they can access all of them. Maybe we should guard against that, like by default don't show anything, and require a special state code to see all states?

2. Is it possible for a user to be in multiple states? Or should we not worry about this for now?

3. This feature will prevent the average user from accessing other states' data. In theory they could still call our endpoints with different state parameters or maybe modify the Javascript to allow load other state pages, would that be unacceptable?

**Comment by terryttsai** [comment]
@phenggeler Security question for you: I have a front-end [PR](https://github.com/Recidiviz/public-dashboard/pull/544) up to only show the tenant/state of the dashboard that the user belongs to (for example, a contact from the North Dakota logs into Spotlight staging should only see North Dakota).

Technically, a logged-in user could inspect the networks and figure out the parameters to send to get metrics for other states on Spotlight staging. But it seems highly unlikely that someone with a Spotlight staging account would have the interest or expertise to do that. Is it worth preventing users from requesting other states' data on the backend?

**Comment by phenggeler** [comment]
Hi @terryttsai - yes, please do prevent users from requesting other states' data on the backend. This has come up previously in penetration tests I believe. You might talk to @jovergaag about how Polaris has dealt with this in the past. 

Please let me know if I am wrong here though, but I think we'd want to ensure access to one account wouldn't allow a user to pivot to other states' metrics.

**Comment by jovergaag** [comment]
@terryttsai We use this `validateStateCode` logic in the server to ensure that the user's state_code matches the state_code in the network request. You could probably copy some/most of this logic.

https://github.com/Recidiviz/pulse-dashboard/blob/main/server/utils/validateStateCode.js

**Comment by terryttsai** [comment]
So for the backend side of things, I'm trying to authenticate the metrics endpoint with a JWT token. I don't know how to do that, but I tried taking code from the pulse-dashboard. For the server, I added this to app.js:
```
const checkJwt = jwt({
  secret: jwksRsa.expressJwtSecret({
    cache: true,
    rateLimit: true,
    jwksRequestsPerMinute: 5,
    jwksUri: `https://${"recidiviz-spotlight-staging.us.auth0.com"}/.well-known/jwks.json`,
  }),

  audience: "ID9plpd8j4vaUin9rPTGxWlJoknSkDX1", // not sure what the audience is
  issuer: `https://${"recidiviz-spotlight-staging.us.auth0.com"}/`,
  algorithms: ["RS256"],
});

app.use(checkJwt);
```

and in the frontend app I'm basically calling the endpoint like this:
```
  const token = await auth0.getTokenSilently()
  const response = await fetch(
    `${process.env.REACT_APP_API_URL}/api/${tenantId}/public`,
    {
      body: JSON.stringify({
        metrics: metricNames,
      }),
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      method: "POST",
    }
  );
```

But the error I get in the backend is `jwt malformed`. Indeed when I decode the token I got from `auth0.getTokenSilently()` in jwt.io, I see this as the header:

```
{
  "alg": "dir",
  "enc": "A256GCM",
  "iss": "https://spotlight-login-staging.recidiviz.org/"
}
```
and no payload.

**Comment by terryttsai** [comment]
I think I should take a step back and ask, how would you authenticate a user in the app? Is it sufficient to pass in the token that we get from `auth0.getTokenSilently()`?

**Comment by macfarlandian** [comment]
I don't know whether this is the problem but the "audience" should not be the client ID, it should be the identifier of an "API" that you define in the Auth0 config (which will be a URL). It looks like you still need to complete that step. 

To your larger point, I do think this is generally the right approach? If we didn't send this in the token we would have to call out to the Auth0 management API service on every request, which I would think is not desirable for performance and error-potential reasons?

**Comment by lilidworkin** [comment]
@terryttsai , now that I think about it, I think we might actually have to create a new API in the spotlight-staging tenant:
<img width="1399" alt="Screen Shot 2022-05-02 at 11 55 11 AM" src="https://user-images.githubusercontent.com/99899591/166307827-1c284619-3d66-4298-a490-62fc3698ad64.png">

**Comment by macfarlandian** [comment]
yes that is what I was referring to, sorry if that wasn't clear!

**Comment by terryttsai** [comment]
Merged the PR, I think I should go ahead and change the staging env files in 1password and re-deploy?

**Comment by lilidworkin** [comment]
@terryttsai yea I think so!! Let me know if you want to do that together

**Comment by terryttsai** [comment]
@hobuobi Just deployed the spotlight backend! This should be good to go, I tested this on https://spotlight-staging.recidiviz.org :)
