### ISSUE TITLE
04/22/2022 - `npm` vulnerabilities 

### ISSUE THREAD

**Issue by phenggeler** [Recidiviz/public-dashboard#542]
---
due: 2022-05-22
--- 
    
Please address the Dependabot `npm` [vulnerabilities](https://github.com/Recidiviz/public-dashboard/security/dependabot?page=1&q=is%3Aopen) in this repository.

**Comment by phenggeler** [comment]
@hobuobi / @macfarlandian / @Catacola - we had a nearly 50 NPM vulnerabilities hit this repo this week. Would you please make sure these are addressed in the next 30 days. Thanks!

**Comment by phenggeler** [comment]
@phenggeler - label applied: Due this month.

**Comment by macfarlandian** [comment]
I _think_ (but others may disagree) that @lilidworkin and her team should be the primary assignees for Dependabot issues in this repo from now on, as they are starting to take over more ownership of Spotlight? I don't mind looking into these though if they need the support, it seems to be mostly the usual false positives anyway

**Comment by lilidworkin** [comment]
I'm fine with that! Can I get some context on what this is / how to address these / what I should be looking for, etc?

**Comment by phenggeler** [comment]
Thanks @lilidworkin
