### ISSUE TITLE
Rotate Auth0 key for Spotlight staging

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/public-dashboard#547]
You are receiving this email because the signing key you're currently using for tenant "recidiviz-spotlight-staging" at "pus3" is more than one year old. We at Auth0 encourage you to rotate the key. After you rotate the key and verify that everything works as expected, you must revoke the old key.

The process is simple:
* Go to Auth0 Dashboard > Settings > Signing Keys.
* Click Rotate Key.
* Accept the rotation.

After rotation, the key identified as next in queue will be used for new signatures. Note that your previous key is still valid and you'll need to manually revoke it after you ensure that all your applications are no longer using it. This will be the case if you're using our libraries.

**Comment by lilidworkin** [comment]
@phenggeler , @macfarlandian , @terryttsai , my understanding from doing some reading on this is that it should be safe for me just to click the "rotate and revoke button" in the Auth0 dashboard, but I wanted to confirm with you all
<img width="970" alt="Screen Shot 2022-05-04 at 10 11 52 AM" src="https://user-images.githubusercontent.com/99899591/166742293-2472fdb2-872c-4056-9ba5-49735186e3f4.png">

The reason I think this is safe is that, until @terryttsai 's [new PR goes in](https://github.com/Recidiviz/public-dashboard/pull/546/files), we haven't even been using tokens / JWT keys in spotlight staging. Auth has only been applied at the frontend layer. So no tokens have been issued with the old key, and it should be safe to replace it with a new one.

Does that make sense to folks? If so I'll go ahead and do the rotation/revocation. Thanks!

**Comment by macfarlandian** [comment]
sounds right to me? either way it only affects us internally so it won't be disruptive to users even if we're wrong 😎
