### ISSUE TITLE
[ID] Staging Copy Cleanup Tasks

### ISSUE THREAD

**Issue by hobuobi** [Recidiviz/public-dashboard#567]
A few quick things to do sooner rather than later, ideally before sharing the staging site with IDOC leadership. 
- P0: Remove the "Can programming help reduce disparities?" section from the Racial Disparities section completely. 
- P0: Remove the following sentences from the Racial Disparities page ("How can parole grant rates impact disparities?") 
    - "In 2019, under guidance from Governor Burgum and then-Director of Corrections Leann Bertsch, the DOC and the Parole Board began tracking and reporting racial data for the parole process in order to monitor and reduce disparities in the population granted parole."
- P1: Calculate recidivism for ID 
    - [Closed PR](https://github.com/Recidiviz/recidiviz-data/pull/12334) basically had this. Should still be done with sessions eventually, but given low bandwidth from state pod DAs, we could just use the old method for now and note the tech debt. Still lower priority for immediate follow-up.

@ldfielding to review this list and add to it if there is anything else to do. Note that the recidivism plots are out of scope for a quick follow-up.

**Comment by terryttsai** [comment]
<img width="1286" alt="Screen Shot 2022-05-09 at 2 34 31 PM" src="https://user-images.githubusercontent.com/5040739/167502376-6d35b6ec-be08-4ea6-b6ca-d33d33cc23ac.png">
How about this section in Idaho Racial Disparities?

**Comment by ldfielding** [comment]
Let's leave that one! I am going to ask them what (if anything) they'd want to add - if they have nothing, then we can cut.
