### ISSUE TITLE
Chart titles are missing in demographic breakdown viz

### ISSUE THREAD

**Issue by macfarlandian** [Recidiviz/public-dashboard#571]
**Describe the bug**
When viewing a demographic breakdown section (e.g., https://spotlight-staging.recidiviz.org/us-nd/narratives/probation/5), labels are missing on all but the last chart when you select a breakdown type.

**To Reproduce**
1. Go to https://spotlight-staging.recidiviz.org/us-nd/narratives/probation/5
2. Click on the dropdown and select one of the demographic types

**Expected behavior**
Only the last chart should have a legend but all of the charts should have a title

**Screenshots**
Screenshots revealing sensitive information _must not_ be shared. If a screenshot is helpful in diagnosing and resolving the bug, please send this directly to a contact on the Recidiviz team.
![Screen Shot 2022-05-27 at 11 17 22 AM](https://user-images.githubusercontent.com/5385319/170768616-b0e65c93-38a6-4fec-af91-e51b733365c3.png)
(this is not sensitive data)

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10]: n/a
 - Browser [e.g. chrome, edge]: 
 - Version [e.g. 22]: 

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]: n/a
 - OS: [e.g. iOS8.1]: 
 - Browser [e.g. stock browser, safari]: 
 - Version [e.g. 22]: 

**Additional context**
Not evident in prod yet so it must be the result of an unreleased change (I believe https://github.com/Recidiviz/public-dashboard/commit/6dc855249dbd20befea052d8a25fef8860b159c2) ... it [appears](https://github.com/Recidiviz/public-dashboard/blob/main/spotlight-client/src/charts/ProportionalBar.tsx#L141) that the prop that hides the legend is also inadvertently hiding the title in this situation)

**Comment by lilidworkin** [comment]
@terryttsai can you look into this when you have a chance, or maybe just assign to Ilya since according to the "Additional Context" it seems like it might be the result of one of his changes!

**Comment by lilidworkin** [comment]
Thank you @nasaownsky !!

**Comment by terryttsai** [comment]
Huh I thought I replied to this via email but I don't see my comment. I have a fix for this too: https://github.com/Recidiviz/public-dashboard/pull/573

Though poking around in the app, I see areas where we provide a legend on every bar rather than on the last bar, do we want to remove the legend in those places too?

**Comment by terryttsai** [comment]
In the racial disparities section:

<img width="1470" alt="Screen Shot 2022-05-31 at 10 02 14 AM" src="https://user-images.githubusercontent.com/5040739/171232067-c67ddb5f-8f12-45f9-9fb1-0dc1193e33a4.png">
<img width="1026" alt="Screen Shot 2022-05-31 at 10 02 19 AM" src="https://user-images.githubusercontent.com/5040739/171232076-161219ed-d916-4fbb-9aa0-0f9f63ba265c.png">
<img width="980" alt="Screen Shot 2022-05-31 at 10 02 24 AM" src="https://user-images.githubusercontent.com/5040739/171232079-ab317a6a-c106-4f17-9cf6-0fabeabfa1f2.png">

**Comment by macfarlandian** [comment]
yes I agree the desired behavior in these scenarios would be to only show the legend once, since it's the same for both charts in the section

**Comment by lilidworkin** [comment]
@terryttsai  what's the status on this?

**Comment by terryttsai** [comment]
PR https://github.com/Recidiviz/public-dashboard/pull/573 is up for fixing the issue however we should create a new issue for removing the legends in areas where they're showing up more than once.

**Comment by terryttsai** [comment]
I'll create the follow-up issue and merge #573

**Comment by lilidworkin** [comment]
Thanks!!

**Comment by terryttsai** [comment]
Follow-up issue: https://github.com/Recidiviz/public-dashboard/issues/575
