### ISSUE TITLE
[US_ID][Pre-launch] Fix broken Sentencing and Probation "Judicial District" dropdowns (or remove them)

### ISSUE THREAD

**Issue by lilidworkin** [Recidiviz/public-dashboard#582]
**Describe the bug**
All Judicial District dropdowns on the Sentencing and Probation narratives don't work. This is because they both reference the `judicialDistricts` variable, which is [empty](https://github.com/Recidiviz/public-dashboard/blob/12a227a1a10958a1f282bfe79f2f17f5d87f3863/spotlight-client/src/contentApi/sources/us_id.ts#L22).

**To Reproduce**
1. Go to 'https://spotlight-staging.recidiviz.org/us-id/narratives/sentencing/1 or https://spotlight-staging.recidiviz.org/us-id/narratives/probation/1
2. Click on any Judicial District dropdown

**Expected behavior**
You can select different Judicial Districts.

**Additional context**
I think this is because our metric files for Sentencing and Probation don't contain complete district information. You can see the metric files in GCS [here](https://console.cloud.google.com/storage/browser/recidiviz-staging-public-dashboard-data/US_ID?project=recidiviz-staging&pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false). For instance, `sentence_type_by_district_by_demographics.json` only has values of ALL or EXTERNAL_UNKNOWN for the district field. Once we update the pipelines that generate these files, we can update [us_id.ts](https://github.com/Recidiviz/public-dashboard/blob/230237b7c99f2acacc2306f2a1a3251770d43485/spotlight-client/src/contentApi/sources/us_id.ts) accordingly.

If it's difficult to add this data, we should just remove this dropdown.

**Comment by jkgerig** [comment]
Not high priority for ID leadership, we should just remove this option.
