### ISSUE TITLE
Overlapping Markers on Maps

### ISSUE THREAD

**Issue by sprad** [Recidiviz/public-dashboard#73]
As I was working on #46 I discovered that many of the facilities are clustered close together and end up overlapping one another.  This makes it difficult, if not impossible, to click the facilities on the map.  See the screenshot below:

<img width="1064" alt="Screen Shot 2020-07-26 at 9 38 42 PM" src="https://user-images.githubusercontent.com/25503/88495637-86a9d380-cf88-11ea-92de-cc0a09f10a08.png">

Ideally we can find a solution to work around this problem.  One possible, although not great approach, could be to stack the markers such that the least populated facilities (i.e smallest dots) are the "closest" and the most populated facilities (i.e. biggest dots) are the furthest.  This would at least provide some room for each marker to be clickable, but I suspect this experience would be particularly cumbersome on mobile.

**Comment by sprad** [comment]
cc  @hobuobi

**Comment by jessex** [comment]
This problem exists in the Pulse Dashboard and we "solve" it by just having the smallest circles on the front and the largest circles on the back, but Pulse Dashboard doesn't pay much attention to mobile users at the moment so, as you say, it may not work great for mobile.

**Comment by sprad** [comment]
I spoke with Juan about this yesterday and we haven't yet arrived at a solution to this problem.  One way to fix it would be to allow the users to zoom in on the map, but we agreed that this solution is out of scope for now.

**Comment by sprad** [comment]
For launch, we're going to go with the stacking approach.  Users on mobile will still be able to use the dropdown control to select offices and facilities for now.
